import { SessionProvider } from 'next-auth/react';
import { Suspense } from 'react';
import { Toaster } from 'sonner';
import SignOutButton from './signout-button';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <>
      <SessionProvider>
        <main className="">
          <nav className="sticky top-0 flex justify-between border-b items-center px-6 min-h-16">
            <a href="/" className="font-bold">
              {process.env.NEXT_PUBLIC_APP_NAME}
            </a>
            <div className="flex gap-3 items-baseline">
              <SignOutButton />
            </div>
          </nav>
          <Suspense fallback={null}>{children}</Suspense>
        </main>
        <Toaster closeButton />
      </SessionProvider>
    </>
  );
}
